---
title: "mixedmodel2"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lme4)
library(Matrix)
library(tidyverse)
library(lmerTest)
library(leaps)
```


```{r cars}
setwd("C:/Users/Ava/OneDrive - Colorado School of Mines/Desktop/Mines/Year4/Semester2/Stat Practicum")
foam_data <- read.csv("foamData.csv")
```

```{r}
foam_data_scaled <- foam_data |>
  filter(cycle <= 10000 & cycle > 0) 
```

```{r}
head(foam_data_scaled)
```

```{r}
coolModel <- lmer(stiffnessFrac ~ porosity + chemIndex + freq + amp + porosity:chemIndex + sqrt_cycle + (porosity + chemIndex + freq + amp + porosity:chemIndex):sqrt_cycle  + (1+sqrt_cycle|ID), data=foam_data_scaled)

summary(coolModel)
anova(coolModel)
plot(coolModel)
```


```{r}
coolModel2 <- lmer(stiffnessFrac ~ chemIndex + freq + amp + sqrt_cycle + (chemIndex + freq + amp):sqrt_cycle  + (1+sqrt_cycle|ID), data=foam_data_scaled)

summary(coolModel2)
anova(coolModel2)
plot(coolModel2)
```
```{r}
# forward selection
regfit.fwd <- regsubsets(stiffnessFrac ~ ID + chemIndex + porosity + freq + amp + initialStrain + initialStress + cycle, data = foam_data_scaled, nvmax = 19, method = "forward")

summary(regfit.fwd)
```
```{r}
regfit.fwd <- regsubsets(log(dampingFrac) ~ ID + chemIndex + porosity + freq + amp + initialStrain + initialStress + log(cycle), data = foam_data_scaled, nvmax = 19, method = "forward")

summary(regfit.fwd)
```


```{r}
regfit.full <- regsubsets(log(dampingFrac) ~ chemIndex + porosity + freq + amp + initialStrain + initialStress + log(cycle) + chemIndex:porosity + (chemIndex + porosity + freq + amp + initialStrain + initialStress + chemIndex:porosity)*log(cycle) + (1 + log(cycle)|ID), data = foam_data_scaled)

plot(regfit.full, scale = "r2")
plot(regfit.full, scale = "adjr2")
plot(regfit.full, scale = "Cp")
plot(regfit.full, scale = "bic")

```

```{r}
BICmodelD <- lmer(log(dampingFrac) ~ porosity + chemIndex + freq + log(cycle) + porosity:log(cycle) + freq:log(cycle) + chemIndex:log(cycle) + (1 + log(cycle)|ID), data = foam_data_scaled)


summary(BICmodelD)
```

```{r}
plot(BICmodelD)
qqnorm(resid(BICmodelD))
qqline(resid(BICmodelD))
```

```{r}
regfit.full <- regsubsets(log(stiffnessFrac) ~ chemIndex + porosity + freq + amp + initialStrain + initialStress + log(cycle) + (chemIndex + porosity + freq + amp + initialStrain + initialStress)*log(cycle) + (1 + log(cycle)|ID), data = foam_data_scaled)

plot(regfit.full, scale = "r2")
plot(regfit.full, scale = "adjr2")
plot(regfit.full, scale = "Cp")
plot(regfit.full, scale = "bic")
```

```{r}
BICmodelS <- lmer(log(stiffnessFrac) ~ freq + amp + log(cycle) + freq:log(cycle) + amp:log(cycle) + (1 +log(cycle)|ID), data = foam_data_scaled)


summary(BICmodelD)
```

```{r}
plot(BICmodelS)
qqnorm(resid(BICmodelS))
qqline(resid(BICmodelS))
```